### ISSUE TITLE
filename difference between template and output

### ISSUE THREAD

**Issue by matthewferry** [FontCustom/fontcustom#122]
First of all, the latest release is awesome.  HUGE improvements across the board. The config.yml file is so much better.

One question though: is it possible with this release to specify a different name for the generated css output?  I'm using a custom template, but would prefer to keep the filenames distinct since one is in production and the other is not. Right now, it just grabs the name of the template I reference in `templates: []`

**Comment by TrevorSayre** [comment]
I also have a custom template living in a resources folder that doesn't go to production. When the template is compiled, I have to run a mv command to put it in the production directory and give it a name that better fits it no longer being a template but an output for production.

:+1:

**Comment by Undistraction** [comment]
This would be really helpful. Tying the filename to the font-name is very restrictive.

**Comment by EugeneDae** [comment]
👍  I miss this functionality.
