### ISSUE TITLE
Fontcustom compile – fontforge compilation failing

### ISSUE THREAD

**Issue by webinsation** [FontCustom/fontcustom#135]
Hey Guys, thanks for this awesome tool – it has been wonderful until this morning!

I tried to compile my icons and it gave me a strange error:

Calebs-iMac:flat caleb$ fontcustom compile fonts/src --debug
        <code>status  Loading configuration file at `fontcustom.yml`.
         debug  Copyright (c) 2000-2012 by George Williams.
        Executable based on sources from 14:57 GMT 31-Jul-2012-D.
        Library based on sources from 14:57 GMT 31-Jul-2012.

```
          []
   error  `fontforge` compilation failed.</code>
```

![image](https://f.cloud.github.com/assets/3697586/1422413/0ef1a33c-3ffb-11e3-94cc-2d307f983757.png)

I tried removing everything – fontforge, ttfautohint, and the fontcustom gem, reinstalling them and it didn’t work.

Any ideas on what the problem is?
Thanks,
– Caleb

**Comment by fotografi** [comment]
>
