### ISSUE TITLE
Fixed-width glyphs

### ISSUE THREAD

**Issue by jlong** [FontCustom/fontcustom#136]
It seems like FontCustom calculates the width of each glyph based on the shapes and not on the canvas area of the SVG. This makes it difficult to achieve pixel perfect centering of glyphs inside of the icon. For example, if I use the following CSS for the icon:

```
.icon {
    text: center;
    font-size: 24px;
    line-height: 24px;
    width: 24px;
    height: 24px;
}
```

It will render slightly blurred if the width of the glyph is 7 pixels because:

```
(24px - 7px) / 2 = 8.5px
```

Causing the icon to be aligned on a half pixel.

**Comment by moll** [comment]
Just stumbled upon a similar problem where I wanted the glyph width to be larger than the shapes in the glyph, but less than the `font_em`. Disabling `autowidth` makes every glyph exactly `font_em` in width, enabling it reduces their width to what their shapes dictate. Both options seem to ignore the SVG canvas size. Am I getting this wrong?
