### ISSUE TITLE
Help, not getting any output.

### ISSUE THREAD

**Issue by mchudnov** [FontCustom/fontcustom#159]
Hello,

I am trying to use fontcustom to create some icons to use on a new webpage.  Admittedly I don't have a lot of experience with stuff like this, but have followed instructions and searched the web for solutions.

As far as I can tell I've installed everything and things should work.

I can run/create the config file (in the directory where my *.svg files are found, but I can't compile the files and get any kind of output.

What am I doing wrong?  Any help you give would be greatly appreciated.

I'm sure you'll need some more info, but not sure what to give, but will send any information you require.

Thanks in advance!

**Comment by fotografi** [comment]
.
