### ISSUE TITLE
Possibility to choose your character map per icon

### ISSUE THREAD

**Issue by yvesvanbroekhoven** [FontCustom/fontcustom#20]
Hi,

is it possible to choose which character is assigned to an icon?

**Comment by pvinis** [comment]
is that still working? how do i use that? the link is dead

**Comment by kaplan** [comment]
@pvinis i was also trying to figure how to change the codepoint. i think i got it and have a gist to detail the workflow. https://gist.github.com/kaplan/8e0cdfa7683e61371698
