### ISSUE TITLE
Not EOT file generated (Maverick 10.9.3)

### ISSUE THREAD

**Issue by dantahoua** [FontCustom/fontcustom#206]
Despite fontcustom saying "status  Forcing compile.
      create  /Volumes/Dev Studio12/Font-Icon/FontCustom/fontcustom.ttf
              /Volumes/Dev Studio12/Font-Icon/FontCustom/fontcustom.svg
              /Volumes/Dev Studio12/Font-Icon/FontCustom/fontcustom.woff
              /Volumes/Dev Studio12/Font-Icon/FontCustom/fontcustom.eot
      create  /Volumes/Dev Studio12/Font-Icon/FontCustom/fontcustom.css
              /Volumes/Dev Studio12/Font-Icon/FontCustom/fontcustom-preview.html"
The EOT file is not there. I realize that I didn't installed "eot-utils" so I installed it then "sudo gem install fontcustom" again, but there is still this small problem... No EOT file generated...

**Comment by julianshowshappening** [comment]
I am having the same issue. Did you find a fix?
