### ISSUE TITLE
Alias

### ISSUE THREAD

**Issue by rafaelfaria** [FontCustom/fontcustom#218]
is there any way to create alias to icons, like font awesome does? I mean, automatically? 

Maybe include in the config.

**Comment by cerdiogenes** [comment]
Take a look at http://fontawesome.io/icons/ at the "dashboard" icon. There is an (alias) in front of it. It's the same as "tachometer".

These aren't two different characters. There is two rules in CSS with the same content: https://github.com/FortAwesome/Font-Awesome/blob/master/css/font-awesome.css#L802

What do you think about using symbolic links as an abstraction to alias? If a dir has a symbolic link to another svg file, the symbolic link name is added to CSS as in link above.

**Comment by cerdiogenes** [comment]
I made a gist with a patch to show a possible implementation: https://gist.github.com/233fecc5db6b73012ada. If this is a desired feature I can make a pull request.

**Comment by jugyhead** [comment]
I would love this feature!
