### ISSUE TITLE
Line height (or something) is crazy in Chrome Version 38.0.2125.101.

### ISSUE THREAD

**Issue by pyroblue** [FontCustom/fontcustom#235]
Let me start off by saying, i LOVE FontCustom.  Thank you for making this, it's helped us incredibly to reduce images, http calls, and afforded us a tremendous amount of flexibility. 

So here's the deal...

I went to bed and stuff was looking fine.  Woke up, and things were not looking so hot. It looked like all of my icons had disappeared!  Turns out they were there, just off the screen in the cases where overflow was set to "hidden"...

Upon further investigation, it would appear that the line-height or something of the .woff files seems to be screwed up in the latest Chrome update.  I've confirmed this across multiple machines.  This issue does not present itself in Safari (OSX) or Firefox (OSX)... 

I've added a link to a zip file containing all of our generated fonts / css / etc. just in case it can be of use...
http://pyroblue-temp.s3.amazonaws.com/fc.zip

THANK YOU for any input you may have on this...
-kasey
## Steps I've taken:
1. I've eliminated all other CSS, aside from fontcustom css, effectively isolating it and removing the possibility of any interference from conflicting styles
2. I've regenerated the font files several times.
3. Uninstalled and reinstalled Chrome and wiped every spec of Chrome preferences on my machine
4. Reverted my code back to several months ago, where i KNOW things were fine (stuff that is now in  production)
5. Used the app on https://icomoon.io/ to generate new font files and css, and it works fine.
## Screenshots and video

I took a screencast using Jing (so unfortunately, it's a SWF)...but hopefully it helps...you should be able to just drag it into a browser.

http://pyroblue-temp.s3.amazonaws.com/2014-10-09_2152.swf

![font-custom-on-left-font-awesome-on-right](https://cloud.githubusercontent.com/assets/29082/4597135/c43b2478-50aa-11e4-85da-8c5e5db3a51e.png)
![font-used-to-be-in-this-circle-now-higher](https://cloud.githubusercontent.com/assets/29082/4597136/c4423ca4-50aa-11e4-95f6-af0392703d9a.png)
![preview](https://cloud.githubusercontent.com/assets/29082/4597064/2b24f0ac-50aa-11e4-8609-61b88de70aa2.png)
![preview2](https://cloud.githubusercontent.com/assets/29082/4597063/2b223204-50aa-11e4-8166-042b57ac9f34.png)

**Comment by local-girl** [comment]
I am also seeing this issue and it isn't resolved with any of the techniques you described.

**Comment by local-girl** [comment]
<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
         width="792" height="792" viewBox="0 0 792 792" enable-background="new 0 0 792 792" xml:space="preserve">
<g>
        <path fill="#808080" d="M566.712,195.264V597.96h-342.72c-17.136,0-34.272-7.344-44.064-20.808L53.856,420.48
                c-11.016-13.465-11.016-34.272,0-48.96l124.848-155.448c9.792-12.24,26.928-20.808,44.064-20.808H566.712 M591.192,170.784h-367.2
                c-24.48,0-47.736,11.016-63.648,29.376L35.496,355.608c-18.36,24.48-18.36,57.528,0,79.56L160.344,591.84
                c14.688,18.36,39.168,29.376,63.648,29.376h367.2V170.784L591.192,170.784z"/>
</g>
</svg>

**Comment by local-girl** [comment]
```
<?xml version="1.0" encoding="utf-8"?>
<!-- Generator: Adobe Illustrator 16.0.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
         width="792" height="792" viewBox="0 0 792 792" enable-background="new 0 0 792 792" xml:space="preserve">
<g>
        <path fill="#808080" d="M566.712,195.264V597.96h-342.72c-17.136,0-34.272-7.344-44.064-20.808L53.856,420.48
                c-11.016-13.465-11.016-34.272,0-48.96l124.848-155.448c9.792-12.24,26.928-20.808,44.064-20.808H566.712 M591.192,170.784h-367.2
                c-24.48,0-47.736,11.016-63.648,29.376L35.496,355.608c-18.36,24.48-18.36,57.528,0,79.56L160.344,591.84
                c14.688,18.36,39.168,29.376,63.648,29.376h367.2V170.784L591.192,170.784z"/>
</g>
</svg>
```

**Comment by pyroblue** [comment]
I have an additional screenshot with more data, and have attached a few of the SVGs I'm using.


SVG's here: http://pyroblue-temp.s3.amazonaws.com/svg-files.zip


**Here's what the font looks like in FontForge**

![screen shot 2015-01-24 at 11 40 07 pm](https://cloud.githubusercontent.com/assets/29082/5942268/164bfe18-a6dc-11e4-9f3e-82cbea3c98cc.png)

**Comment by pyroblue** [comment]
@endtwist is there anyway we can reopen this issue or at least give me some guidance as to why this might be happening?  the viewbox didnt seem to fix it...

much appreciated!

**Comment by dnlmzw** [comment]
I'm experiencing some error with Chrome 40.0.2214.115 that looks related to this as well. http://i.imgur.com/okm0AmY.png

**Comment by jaukia** [comment]
+1, having similar issues with Chrome 40.0.2214.115 as well.

**Comment by dnlmzw** [comment]
My workaround for now (though very hacky and only tested in the latest version of FF, Safari, Chrome and Safari and Chrome for iOS) was to use a Chrome specific media query.

```css
@media all and (-webkit-min-device-pixel-ratio:0) and (min-resolution: .001dpcm) {
  line-height: 8px;
}
```

**Comment by jaukia** [comment]
I had some glyphs in the input SVG files that were probably outside the SVG bounds. I removed them manually in a text editor and now the icons work correctly in all browsers. The issue showed up only on Chrome, not on Firefox or on Safari. It would be great if fontcustom would automatically detect off-canvas vertices and warn about them or remove them.

**Comment by JohnnyEvo** [comment]
+1 with Chrome 41.0.2272.104 (64-bit)

@see http://stackoverflow.com/questions/29102732/custom-font-extra-height-with-chrome

**Comment by dnlmzw** [comment]
Shouldn't this ticket be re-opened?

**Comment by pyroblue** [comment]
i agree with @dnlmzw - from my investigation, it appears to be some sort of issue with fontforge, though. not sure if FontCustom's implementation / use of it is the issue or not...

**Comment by felipepalazzo** [comment]
+1 with Chrome Version 43.0.2357.130 (64-bit)

**Comment by tjeden** [comment]
We had the same issue as @jaukia (thank you for help). One SVG was outside the SVG bounds, and line height was invalidon Chrome. Fixing SVG helped.

**Comment by Landish** [comment]
+1 in Chrome `Version 47.0.2526.106 (64-bit)`.

**Comment by DorienD** [comment]
+1 in Chrome 52.0.2743.116 (64-bit). Did anyone find a workaround for this?

**Comment by DorienD** [comment]
I have added the svg's that i used on this fontcustom project to icomoon and generated the font. Implemented it in the site and now it works. The svg's all have 0,0 on the viewbox part. So still not sure why this doesn't work with fontcustom.
