### ISSUE TITLE
Watch broken in Yosemite

### ISSUE THREAD

**Issue by linkumx** [FontCustom/fontcustom#251]
Hi, after a fresh install, "watch" doesn't seem to work, eve if I 've reinstalled FontForge, upgraded to the latest Ruby and reintalled eot.

Font Custom is watching your icons. Press Ctrl + C to stop.
       debug  Using settings from `fontcustom.yml`.
       debug  Using options:
                {:input=>
                 {:vectors=>"/Users/ehe/NetBeansProjects/tpad/fontcustom/vector",
                  :templates=>"/Users/ehe/NetBeansProjects/tpad/fontcustom/vector"},
                :output=>{:fonts=>"fonts", :css=>"less", :preview=>"fonts"},
                :config=>"fontcustom.yml",
                :templates=>["css", "preview"],
                :font_name=>"trpdfont",
                :font_design_size=>16,
                :font_em=>512,
                :font_ascent=>448,
                :font_descent=>64,
                :css_selector=>".i_{{glyph}}",
                :preprocessor_path=>"",
                :autowidth=>false,
                :no_hash=>true,
                :debug=>true,
                :force=>false,
                :quiet=>false,
                :skip_first=>false}
      status  No changes detected. Skipping compile.
/Library/Ruby/Gems/2.0.0/gems/fontcustom-1.3.5/lib/fontcustom/watcher.rb:51:in `start': undefined method `join' for #<ConditionVariable:0x007fe663895098> (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/fontcustom-1.3.5/lib/fontcustom/watcher.rb:22:in `watch'
	from /Library/Ruby/Gems/2.0.0/gems/fontcustom-1.3.5/lib/fontcustom/cli.rb:87:in `watch'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/fontcustom-1.3.5/bin/fontcustom:5:in `<top (required)>'
	from /usr/bin/fontcustom:23:in `load'
	from /usr/bin/fontcustom:23:in `<main>'

**Comment by stormbeta** [comment]
Having the same issue on OSX 10.10.

`fontcustom compile` still works, but the watch doesn't.

**Comment by zhuangya** [comment]
i meet this problem as well.

but i have my little work around, hopefully can help you guys for now:

`nodemon --exec "fontcustom compile ." -e "svg"`

**Comment by bridgetkilgallon** [comment]
I'm also experiencing this after updating fontcustom today. I've been on Yosemite for a while and watch was working fine with an older version of fontcustom (i think 1.3.0?).
