### ISSUE TITLE
Add WOFF2 font format

### ISSUE THREAD

**Issue by Simek** [FontCustom/fontcustom#253]
tl;dr: support for a better web font compression format called WOFF 2.0 with Brotli is coming in M35. We are seeing a 30% gain over the existing WOFF 1.0 format from an analysis we ran on the whole Google Fonts corpus. The gains were even more impressive for our Asian font corpus where we saw up to 50%+ improvements (median for the whole corpus was at 24% ).

More at:
https://groups.google.com/a/chromium.org/forum/#!topic/chromium-dev/j27Ou4RtvQI/discussion

Spec:
http://www.w3.org/TR/WOFF2/

**Comment by karlhorky** [comment]
:+1: what needs to be done to make this happen?

**Comment by ArdentKid** [comment]
would be nice, especially since I'm combining it with bootstrap (which uses woff2). Currently throwing them into this online tool for conversion https://everythingfonts.com/woff-to-woff2

But obviously this is not a good workflow.

**Comment by schurig** [comment]
would be really nice!

**Comment by karlhorky** [comment]
Maybe this could be done with `woff2_compress` from https://github.com/bramstein/homebrew-webfonttools? This command should convert from ttf to woff2.

**Comment by epegzz** [comment]
+1 :)

**Comment by epegzz** [comment]
also check out this [ttf to woff2 converter](https://github.com/google/woff2) from google

**Comment by abhilashlr** [comment]
any updates on this?

**Comment by mnpenner** [comment]
+1

**Comment by lochstar** [comment]
+1

**Comment by pvolyntsev** [comment]
https://github.com/pvolyntsev/fontcustom/commit/088d904d47ce47d9709da1fa4abda60ae4a87f09

**Added WOFF2 support**

Requires WOFF2 tools
See build instructions at https://github.com/google/woff2
Fontcustom will produce fail if woff2_compres ulility is not installed

Added "woff2" installation instructions for Mac into Readme.md but actually not played with Mac. Hope it works.

**Comment by karlhorky** [comment]
Very cool @pvolyntsev! Did you want to open a PR for this?

**Comment by pvolyntsev** [comment]
@karlhorky Yes, will do

**Comment by Simek** [comment]
WOFF2 format has been added in 2.0.0, closing!
