### ISSUE TITLE
Installation fails downloading libpng dependancy due to certificate errors

### ISSUE THREAD

**Issue by MeltedYeti** [FontCustom/fontcustom#262]
==> Installing dependencies for fontforge: libpng, jpeg, libtiff, freetype, fontconfig
==> Installing fontforge dependency: libpng
==> Downloading https://downloads.sf.net/project/libpng/libpng16/1.6.13/libpng-1.6.13.tar.xz

curl: (60) SSL certificate problem: Invalid certificate chain
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
Error: Failed to download resource "libpng"
Download failed: https://downloads.sf.net/project/libpng/libpng16/1.6.13/libpng-1.6.13.tar.xz

Is there a way to override the install scripts, or a better way to get around this?

**Comment by kaizau** [comment]
Perhaps try this: https://stackoverflow.com/questions/18964175/how-to-fix-curl-60-ssl-certificate-invalid-certificate-chain
