### ISSUE TITLE
Custom template "bootstrap" wasn't found

### ISSUE THREAD

**Issue by EugeneDae** [FontCustom/fontcustom#265]
I've wasted half an hour trying to figure out why I'm getting:

    error  Custom template `bootstrap` wasn't found in `static/icons/svg/`. Check your options.

when trying to use `--templates="bootstrap"`. 

Fontcustom.com says it's built-in. Turns out it's not.

Please update your website or at least add a notice telling where to look for the up-to-date documentation.

**Comment by kaizau** [comment]
Hey, sorry for that — fixed.
