### ISSUE TITLE
FontCustom Won't install - Mac OS X Sierra.

### ISSUE THREAD

**Issue by pixelSpectrum** [FontCustom/fontcustom#324]
I've gone through and setup everything I could to get to the point of installing Font Custom (gem install fontcustom), but it won't install.  Does anyone have an idea how t fix it?

I thought it was El Capitan, but still got nothing with Sierra the same error.  I used http://railsapps.github.io/installrubyonrails-mac.html to install ruby and gems before...
brew install fontforge --with-python
brew install eot-utils
gem install fontcustom

Everything installed fine except  gem install fontcustom or sudo geminstall fontcustom, both give the error below.

error:
6 warnings and 2 errors generated.
make: *** [generator.o] Error 1
make failed, exit code 2
Gem files will remain installed in /Users/MacHD/.rvm/gems/ruby-2.4.0@rails5.0/gems/json-1.8.3 for inspection.

**Comment by JeffersonVectto** [comment]
you need to install the ruby.2.4-dev and run the gem again.
