### ISSUE TITLE
How to integrate to laravel project

### ISSUE THREAD

**Issue by JeffersonVectto** [FontCustom/fontcustom#328]
I was able to run the project in my local machine, I was wondering if has anyone able to integrate this to a laravel project?

Instead of generating a preview.html is there anyway to serve the generated to a route? Thanks!

**Comment by JakeBeresford** [comment]
This is a ruby gem, so it will not work with Laravel. There are other, similar solutions that you may be able to use depending on your front-end stack. https://www.npmjs.com/package/gulp-iconfont for example.
