### ISSUE TITLE
Generated fonts have unequal top- & bottom-whitespace

### ISSUE THREAD

**Issue by timhettler** [FontCustom/fontcustom#33]
When I compile, the resulting fonts are not vertically centered.

As they appear in Illustrator:

![Screen Shot 2012-12-17 at 6 31 18 PM](https://f.cloud.github.com/assets/630497/18217/e6059d8a-48a1-11e2-8bd3-1794a1245fc6.png)

...And then as they appear on a webpage:

![Screen Shot 2012-12-17 at 6 33 32 PM](https://f.cloud.github.com/assets/630497/18223/39a48492-48a2-11e2-8f94-b6ace179ad2f.png)

(Deep Pink background added to illustrate unequal whitespace.)

**Comment by ChrisBup** [comment]
Has this issue been resolved? I'm trying to set all icons to a consistent baseline no matter their width and can't figure out what to set the font_ascent and font_descent in fontcustom.yml. Thanks.
<img width="613" alt="screen shot 2015-07-09 at 7 19 03 pm" src="https://cloud.githubusercontent.com/assets/7212504/8609092/654b2468-266f-11e5-9635-4184c8dff944.png">
