### ISSUE TITLE
fontcustom --version show error

### ISSUE THREAD

**Issue by sundylink** [FontCustom/fontcustom#344]
`fontcustom --version` and show error:
```
Expected array default value for '--templates'; got "css preview" (string)
fontcustom-2.0.0 
```
@lukemelia  @foca @jlong  @pilif  @mhodgson  thanks !

**Comment by avmax** [comment]
I have same one at any command with fontcustom. How can that be fixed?

**Comment by sfunaro** [comment]
I have the same error!

**Comment by stretchkennedy** [comment]
Looking at https://github.com/FontCustom/fontcustom/blob/c2692117bd8e87bb80dc887c5e7bc076a8053a0e/lib/fontcustom.rb#L22, `:templates => "css preview"` should probably be `:templates => %w|css preview|`

I'll create a PR for this later tonight

**Comment by Philluxx** [comment]
Can confirm this bug.

@stretchkennedy this is really appreciated though fontcustom isn't working anymore. Thank you very much!

**Comment by FerrusDude** [comment]
Can also confirm this bug.

**Comment by JakeBeresford** [comment]
@stretchkennedy Thanks for investigating, if you can open a PR I'll get a patch released ASAP.

**Comment by sundylink** [comment]
Is the bug solved?

**Comment by sfunaro** [comment]
Can someone help on how to update ? gem update don't seem to get this change.
Thanks!

**Comment by sundylink** [comment]
run: `gem install fontcustom` , and show error:

```
ERROR:  Error installing fontcustom:
	ruby_dep requires Ruby version >= 2.2.5, ~> 2.2.
```

**Comment by MUllman** [comment]
So is this fixed?
