### ISSUE TITLE
Linux install doesnt work anymore.

### ISSUE THREAD

**Issue by nhumrich** [FontCustom/fontcustom#345]
Looks like mozilla shut off people.mozilla.com so the link to get the woff font doesnt work anymore.

Any other ideas for how to get the font on linux?

**Comment by senterright** [comment]
To whom it may concern, I found what appears to be a copy of the file in some other open source git repo: https://github.com/instructure/canvas-lms/raw/902fca830d93b2eb1099ef08d031339ec9515abd/build/vendor/woff-code-latest.zip

so running wget should work with that, at least temporarily.
