### ISSUE TITLE
Error: Invalid formula

### ISSUE THREAD

**Issue by insolera** [FontCustom/fontcustom#365]
system: macOS High Sierra 10.13.3
ruby: ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin16]
i got this error:
================
Cloning into '/usr/local/Homebrew/Library/Taps/bramstein/homebrew-webfonttools'...
remote: Counting objects: 11, done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 11 (delta 0), reused 5 (delta 0), pack-reused 0
Unpacking objects: 100% (11/11), done.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/bramstein/homebrew-webfonttools/sfntly.rb
Calling 'depends_on :ant' is disabled!
Use 'depends_on "ant"' instead.
/usr/local/Homebrew/Library/Taps/bramstein/homebrew-webfonttools/sfntly.rb:7:in `<class:Sfntly>'
Please report this to the bramstein/webfonttools tap!
Or, even better, submit a PR to fix it!

================

Any help?

**Comment by filoxo** [comment]
This issue stems from the homebrew-webfonttools project, and has an open pull request to fix it https://github.com/bramstein/homebrew-webfonttools/pull/21

Who knows when it'll be fixed, but here's my temporary solution. 

1. `cd /usr/local/Homebrew/Library/Taps`
2. `git clone https://github.com/bramstein/homebrew-webfonttools.git ./bramstein/homebrew-webfonttools`
3. Modify *sfntly.rb* to fix the syntax error like in the above PR
3. `brew tap bramstein/webfonttools`
