### ISSUE TITLE
Compiling of Inkscape SVG's ok, but no icons are shown in the browser afterwards

### ISSUE THREAD

**Issue by k00ni** [FontCustom/fontcustom#44]
I created some SVGs with **Inkscape 0.48**. After i compiled these with fontcustom it created all the files as you can see here:

![](https://f.cloud.github.com/assets/381727/131470/67dfb6d4-705b-11e2-8da8-a818e7006d54.png)

But after opening the test.html no icons are displayed :(

![](https://f.cloud.github.com/assets/381727/131471/98ee2aa8-705b-11e2-9ea5-6120977bc94f.png)

The SVG's are available as a git repo and can be found [here](https://github.com/k00ni/semicon/tree/master/svg). I guess they are ok, aren't they?

And [here](http://inspirito.de/share/iconfont.tar.bz2) are my compiled files.

Some information about my local machine:
- Ubuntu 12.04
- Installed without **ttfautohint**! But it has to be working without it too, right?
- Inkscape 0.48 for SVG generation
- Tried viewing in browser with Chrome 23 and Firefox 11

**Comment by Tpona** [comment]
Anybody?
@k00ni, @dantman
I have same trouble with FontAwesome SVG-file.
I tried the last solution ```viewBox="0 0 [width] [height]``` but get same error:
> I'm sorry this file is too complex for me to understand (or is erroneous)

Which there is alternative ways, that exclude unused "FA" glyphs?
thx

**Comment by k00ni** [comment]
I have not worked on this issue since my last post here, but i am curious what the developers will say. :)

Kinda regards

**Comment by Tpona** [comment]
I think they stopped development (

**Comment by seanwash** [comment]
I was able to fix this issue for myself by adding the viewbox property to my svg's. Worked like a charm after that! Thanks @k00ni

**Comment by k00ni** [comment]
Hey @seanwash, could you please explain, with a short example, how you fixed that problem? Thanks!

**Comment by seanwash** [comment]
@k00ni I had previously been using a custom Adobe Generator plugin that was exporting a bunch of SVG's from a psd, but none of those svgs had a viewbox property set on them. For some reason w/o the viewbox fontcustom made the icons themselves really really small. I tried exporting some icons from Illustrator, made sure they had view boxes and tried it again. Worked like a charm.
